assigness: []
harvest_options:
  goldcopy: true
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE04OSPD-DP01B-06-DOSTAD105
stream:
  method: recovered_wfp
  name: dpc_optode_instrument_recovered
workflow_config:
  schedule: 0 0 * * *
